import { testBlock } from "bingo-stratum-testers";
import { describe, expect, test } from "vitest";

import { blockREADME } from "./blockREADME.js";
import { optionsBase } from "../options.fakes.js";

describe("blockREADME", () => {
	test("without addons", () => {
		const creation = testBlock(blockREADME, {
			options: optionsBase,
		});

		expect(creation).toMatchInlineSnapshot(`
			{
			  "files": {
			    "README.md": "# test-repository

			Example repository created from create-stratum-example's \`--preset undefined\`. 💕

			## Development

			Requires Node.js LTS.
			After [forking the repo from GitHub](https://help.github.com/articles/fork-a-repo):

			\`\`\`shell
			git clone https://github.com/(your-name-here)/test-repository
			cd test-repository
			npm install
			\`\`\`



			---

			> This repository was generated by [bingo-examples/create-stratum-example](https://github.com/bingo-examples/create-stratum-example) using the [Bingo engine](https://create.bingo).
			",
			  },
			}
		`);
	});

	test("with addons", () => {
		const creation = testBlock(blockREADME, {
			addons: {
				scripts: [
					{
						command: "npm run one",
						description: "Script one.",
						title: "Script One",
					},
					{
						command: "npm run two",
						description: "Script two.",
						title: "Script Two",
					},
				],
			},
			options: optionsBase,
		});

		expect(creation).toMatchInlineSnapshot(`
			{
			  "files": {
			    "README.md": "# test-repository

			Example repository created from create-stratum-example's \`--preset undefined\`. 💕

			## Development

			Requires Node.js LTS.
			After [forking the repo from GitHub](https://help.github.com/articles/fork-a-repo):

			\`\`\`shell
			git clone https://github.com/(your-name-here)/test-repository
			cd test-repository
			npm install
			\`\`\`

			### Script One

			\`\`\`shell
			npm run one
			\`\`\`

			Script one.
				
				

			### Script Two

			\`\`\`shell
			npm run two
			\`\`\`

			Script two.
				
				

			---

			> This repository was generated by [bingo-examples/create-stratum-example](https://github.com/bingo-examples/create-stratum-example) using the [Bingo engine](https://create.bingo).
			",
			  },
			}
		`);
	});
});
